import type { FactType } from "@/entities/types";

export const DOMAINS = [
  {
    id: "finance",
    label: "Finance",
    icon: "💰",
    desc: "Cheque bounce, bank/online fraud, tax disputes, money recovery",
    subtypes: [
      { id: "cheque_bounce", label: "Cheque Bounce (Sec 138)", desc: "Dishonoured cheques and Section 138 NI Act notices" },
      { id: "bank_fraud", label: "Bank / Online Fraud", desc: "UPI scam, phishing, OTP fraud, card cloning" },
      { id: "tax_dispute", label: "Income Tax Dispute", desc: "Refund pending, excess demand notices, TDS mismatches" },
      { id: "money_recovery", label: "Money Recovery / Loan", desc: "Personal or business loan defaults, promissory notes" },
      { id: "other_finance", label: "Other Financial", desc: "Other financial, banking or debt disputes" },
    ]
  },
  {
    id: "consumer",
    label: "Consumer",
    icon: "🛒",
    desc: "Defective products, service deficiency, e-commerce, insurance",
    subtypes: [
      { id: "product_defect", label: "Product Defect", desc: "Defective appliances, electronics, or vehicles under warranty" },
      { id: "service_deficiency", label: "Service Deficiency", desc: "Deficient telecom, banking, insurance, or internet services" },
      { id: "ecommerce_dispute", label: "E-commerce Dispute", desc: "Refund denied, wrong item, or counterfeit goods online" },
      { id: "insurance_rejection", label: "Insurance Claim Rejected", desc: "Rejected health, life, motor, or travel claims" },
      { id: "medical_negligence", label: "Medical Negligence", desc: "Negligent medical care or hospital malpractice" },
    ]
  },
  {
    id: "rera",
    label: "RERA / Property",
    icon: "🏗️",
    desc: "Delayed flat possession, project cancellation, structural defects",
    subtypes: [
      { id: "delayed_possession", label: "Delayed Possession", desc: "Failure of builder to hand over flat on promised date" },
      { id: "project_cancellation", label: "Project Cancellation", desc: "Cancellation of booking or whole housing project" },
      { id: "structural_defects", label: "Structural Defects", desc: "Poor construction quality or defects noticed post-handover" },
      { id: "amenities_misrepresentation", label: "Misrepresentation / Amenities", desc: "Undelivered amenities promised in brochures" },
    ]
  },
  {
    id: "motor_vehicles",
    label: "Motor Vehicles Act",
    icon: "🚗",
    desc: "Road accidents, injury/death claims, RTO disputes",
    subtypes: [
      { id: "accident_injury", label: "Accident — Personal Injury", desc: "Injuries sustained in road traffic accidents" },
      { id: "accident_death", label: "Accident — Death Claim (MACT)", desc: "Fatal road accident compensation petitions before MACT" },
      { id: "mv_insurance_rejection", label: "Insurance Claim Rejected", desc: "Rejected motor own-damage or third-party claims" },
      { id: "hit_and_run", label: "Hit and Run", desc: "Hit & run victim compensation claims under MACT fund" },
      { id: "license_rc_dispute", label: "Driving Licence / RC Dispute", desc: "Suspended licence, RC transfer, or penalty order disputes" },
    ]
  },
  {
    id: "legal_notice",
    label: "Legal Notice",
    icon: "📄",
    desc: "Draft a formal demand or grievance notice to resolve a dispute",
    subtypes: [
      { id: "legal_notice_draft", label: "Legal Notice Service", desc: "Draft a legal notice directly from dashboard" }
    ]
  }
] as const;

export type CategoryId =
  | "cheque_bounce" | "bank_fraud" | "tax_dispute" | "money_recovery" | "other_finance"
  | "product_defect" | "service_deficiency" | "ecommerce_dispute" | "insurance_rejection" | "medical_negligence"
  | "delayed_possession" | "project_cancellation" | "structural_defects" | "amenities_misrepresentation"
  | "accident_injury" | "accident_death" | "mv_insurance_rejection" | "hit_and_run" | "license_rc_dispute";

export type FieldDef = {
  key: string; label: string;
  type: "text" | "number" | "date" | "yesno" | "select";
  placeholder?: string; options?: string[];
};

export const SUBTYPE_FIELDS: Record<CategoryId, FieldDef[]> = {
  cheque_bounce: [
    { key: "cheque_amount",       label: "Amount on the cheque (₹)",            type: "number", placeholder: "e.g. 75000" },
    { key: "cheque_date",         label: "Date written on the cheque",            type: "date" },
    { key: "dishonour_date",      label: "Date it was returned / bounced",        type: "date" },
    { key: "dishonour_reason",    label: "Reason for dishonour",                  type: "select",
      options: ["Insufficient funds", "Payment stopped", "Account closed", "Signature mismatch", "Exceeds arrangement", "Post-dated cheque before date", "Other"] },
    { key: "payee_name",          label: "Payee name",                            type: "text",   placeholder: "e.g. Suresh Kumar" },
    { key: "bank_name",           label: "Drawer's bank name",                    type: "text",   placeholder: "e.g. HDFC Bank" },
    { key: "branch_name",         label: "Drawer's branch",                       type: "text",   placeholder: "e.g. MG Road Branch" },
    { key: "legal_notice_sent",   label: "Was a demand notice sent to the drawer?", type: "yesno" },
    { key: "notice_date",         label: "Notice sent date (if applicable)",      type: "date" },
    { key: "response_15days",     label: "Has 15-day response deadline elapsed?", type: "yesno" },
    { key: "underlying_debt_type",label: "What was the cheque for?",              type: "select",
      options: ["Loan repayment", "Service payment", "Goods payment", "Security deposit", "Other"] },
    { key: "drawer_type",         label: "Who is the drawer?",                    type: "select",
      options: ["Individual", "Company or Partnership"] },
    { key: "notice_sent_by_regd_post", label: "Was notice sent by registered post?", type: "yesno" },
    { key: "cheque_presented_in_validity", label: "Was the cheque presented within its validity period?", type: "yesno" },
    { key: "drawer_company_name", label: "Drawer company/firm name (if applicable)", type: "text", placeholder: "e.g. ABC Pvt Ltd" },
    { key: "cheque_was_security_or_payment", label: "What was the cheque's role?", type: "select",
      options: ["Payment of debt", "Security deposit", "Advance payment"] },
    { key: "financial_capacity_proof_available", label: "Do you have proof of financial capacity to give this loan/goods?", type: "yesno" },
  ],
  bank_fraud: [
    { key: "fraud_type",          label: "Fraud type",                            type: "select",
      options: ["Phishing", "OTP fraud", "UPI fraud", "Card clone", "Account takeover", "Ponzi", "Investment scam (fake trading/job)", "Other"] },
    { key: "amount_defrauded",    label: "Amount defrauded (₹)",                  type: "number", placeholder: "e.g. 1500" },
    { key: "fraud_date",          label: "Date of fraud",                         type: "date" },
    { key: "bank_name",           label: "Bank name",                            type: "text",   placeholder: "e.g. ICICI Bank" },
    { key: "transaction_ref",     label: "Transaction ID / UTR number / UPI transaction ID", type: "text", placeholder: "e.g. UTR1234567" },
    { key: "cybercrime_complaint",label: "Cybercrime complaint filed?",            type: "yesno" },
    { key: "complaint_number",    label: "Complaint number (if filed)",           type: "text",   placeholder: "e.g. 1002345" },
    { key: "bank_response",       label: "Bank response received?",               type: "yesno" },
    { key: "time_to_report_bank", label: "Time elapsed to report to bank",        type: "select",
      options: ["Same day (0-3 hours)", "Within 3 days", "4-7 days", "More than 7 days"] },
    { key: "helpline_1930_called", label: "Was cybersecurity helpline 1930 called?", type: "yesno" },
    { key: "bank_complaint_acknowledged", label: "Was bank complaint formally acknowledged?", type: "yesno" },
    { key: "ombudsman_complaint_filed", label: "Was an RBI Ombudsman complaint filed?", type: "yesno" },
    { key: "amount_frozen_by_bank", label: "Amount frozen in fraudster account (₹)", type: "number", placeholder: "e.g. 10000" },
    { key: "fraud_medium",        label: "Fraud medium",                          type: "select",
      options: ["Phone call", "WhatsApp message", "Email link", "QR code scan", "Social media", "In-person"] },
  ],
  tax_dispute: [
    { key: "assessment_year",     label: "Assessment year",                       type: "text",   placeholder: "e.g. AY 2024-25" },
    { key: "issue_type",          label: "Issue type",                            type: "select",
      options: [
        "Excess demand notice (143(1))",
        "Scrutiny assessment notice (143(2))",
        "Best judgement assessment (144)",
        "Income escaping assessment (148/147)",
        "Refund not processed",
        "TDS mismatch (Form 26AS)",
        "Penalty notice (271)",
        "Stay of demand"
      ] },
    { key: "amount_disputed",     label: "Amount in dispute (₹)",                 type: "number", placeholder: "e.g. 120000" },
    { key: "notice_number",       label: "Notice/Order number",                   type: "text",   placeholder: "e.g. DIN-12345" },
    { key: "auditor_involved",    label: "Is a CA/Auditor involved?",             type: "yesno" },
    { key: "previous_appeal",     label: "Previous appeal filed?",                type: "yesno" },
    { key: "taxpayer_type",       label: "Taxpayer Type",                         type: "select",
      options: ["Individual", "HUF", "Sole proprietor", "Partnership firm", "Private Limited Company"] },
    { key: "notice_section",      label: "Notice Section (e.g., 143(1), 148)",    type: "text",   placeholder: "e.g. 143(2)" },
    { key: "notice_deadline",     label: "Notice response deadline",              type: "date" },
    { key: "itr_filed_for_year",  label: "Was ITR filed for the disputed year?",  type: "yesno" },
    { key: "demand_showing_on_portal", label: "Is demand showing outstanding on portal?", type: "yesno" },
    { key: "tax_paid_under_protest", label: "Has any tax been paid under protest? (₹)", type: "yesno" },
    { key: "gst_or_income_tax",   label: "Tax Domain",                            type: "select",
      options: ["Income Tax", "GST"] },
    { key: "pan_linked_to_case",  label: "Is PAN correctly linked to ITR?",       type: "yesno" },
  ],
  money_recovery: [
    { key: "loan_type",           label: "Type of loan/debt",                     type: "select",
      options: ["Personal loan", "Business loan", "Promissory note", "Part payment", "Other"] },
    { key: "amount_lent",         label: "Amount lent (₹)",                        type: "number", placeholder: "e.g. 300000" },
    { key: "date_lent",           label: "Date lent",                             type: "date" },
    { key: "repayment_date",      label: "Agreed repayment date",                 type: "date" },
    { key: "docs_available",      label: "What documents are available?",         type: "select",
      options: ["Written agreement / promissory note", "WhatsApp/SMS acknowledgement", "Bank transfer proof", "Witness present", "Post-dated cheques received", "No documentation"] },
    { key: "partial_payment",     label: "Partial payment received?",             type: "yesno" },
    { key: "amount_received",     label: "Amount received so far (₹)",            type: "number", placeholder: "e.g. 50000" },
    { key: "cheques_received_from_debtor", label: "Are any cheques received from the debtor?", type: "yesno" },
    { key: "limitation_check",    label: "Is it within 3 years of agreed repayment?", type: "yesno" },
    { key: "debtor_assets_known", label: "Do you know if debtor has realizable assets?", type: "yesno" },
    { key: "interest_agreed",     label: "Was interest rate formally agreed?",    type: "yesno" },
    { key: "interest_rate",       label: "Agreed interest rate (%)",              type: "number", placeholder: "e.g. 12" },
    { key: "witnesses_present",   label: "Were witnesses present during transaction?", type: "yesno" },
    { key: "defendant_employed_or_has_property", label: "Does defendant have property or steady job?", type: "yesno" },
  ],
  other_finance: [
    { key: "dispute_type",        label: "Describe the nature of the dispute",    type: "text",   placeholder: "e.g. Dispute over credit card charges" },
    { key: "amount_involved",     label: "Amount involved (₹)",                   type: "number", placeholder: "e.g. 35000" },
    { key: "forum_needed",        label: "Preferred forum type",                  type: "select",
      options: ["Court / Tribunal", "Regulatory body (RBI, SEBI, IRDA)", "Arbitration", "Not sure"] },
  ],
  product_defect: [
    { key: "product_name",        label: "Product name",                          type: "text",   placeholder: "e.g. Smart TV" },
    { key: "brand",               label: "Brand",                                 type: "text",   placeholder: "e.g. Sony" },
    { key: "purchase_amount",     label: "Purchase amount (₹)",                   type: "number", placeholder: "e.g. 45000" },
    { key: "purchase_date",       label: "Purchase date",                         type: "date" },
    { key: "purchase_channel",    label: "Purchase channel",                      type: "select",
      options: ["Online", "Retail store", "Direct from manufacturer (factory outlet)", "Grey market / unauthorized dealer"] },
    { key: "defect_description",  label: "Defect description",                    type: "text",   placeholder: "e.g. Screen line issue within 1 month" },
    { key: "complaint_sent",      label: "Complaint sent to seller/brand?",       type: "yesno" },
    { key: "complaint_date",      label: "Complaint date",                        type: "date" },
    { key: "company_response",    label: "Company response",                      type: "text",   placeholder: "e.g. Replacement denied" },
    { key: "warranty_valid",      label: "Is the warranty still valid?",          type: "yesno" },
    { key: "relief_sought",       label: "Primary relief sought",                 type: "select",
      options: ["Full refund", "Replacement with new unit", "Free repair", "Compensation for consequential loss"] },
    { key: "escalated_to_nodal_officer", label: "Has the issue been escalated to Nodal officer?", type: "yesno" },
    { key: "service_engineer_visited", label: "Did authorized service engineer inspect defect?", type: "yesno" },
    { key: "e_daakhil_filed",     label: "Was complaint already filed on e-Daakhil?", type: "yesno" },
    { key: "purchase_invoice_available", label: "Is the original purchase invoice available?", type: "yesno" },
  ],
  service_deficiency: [
    { key: "service_type",        label: "Service type",                          type: "select",
      options: ["Telecom", "Banking", "Insurance", "Electricity", "Internet", "Education", "Water/Sanitation (Municipal)", "Railway", "Courier/Logistics", "Other"] },
    { key: "provider_name",       label: "Provider name",                         type: "text",   placeholder: "e.g. Airtel" },
    { key: "issue_description",   label: "Issue description",                     type: "text",   placeholder: "e.g. Broad band down for 10 days" },
    { key: "amount_paid",         label: "Amount paid (₹)",                       type: "number", placeholder: "e.g. 2400" },
    { key: "complaint_sent",      label: "Complaint sent?",                       type: "yesno" },
    { key: "complaint_date",      label: "Date of complaint",                     type: "date" },
    { key: "regulatory_body_complaint_filed", label: "Was complaint filed with regulator? (e.g. TRAI/Ombudsman)", type: "yesno" },
    { key: "nodal_officer_escalated", label: "Was it escalated to company's Nodal Officer?", type: "yesno" },
    { key: "service_still_ongoing_issue", label: "Is the deficiency still ongoing?",   type: "yesno" },
    { key: "documentation_available", label: "What documents are available?",         type: "select",
      options: ["Bills/receipts", "Written complaint acknowledgement", "Email trail", "Telecom service report", "Bank statement showing deductions"] },
  ],
  ecommerce_dispute: [
    { key: "platform",            label: "Platform",                              type: "select",
      options: ["Amazon", "Flipkart", "Meesho", "Myntra", "Swiggy/Zomato", "BookMyShow", "Make My Trip/Goibibo", "Other"] },
    { key: "order_id",            label: "Order ID",                              type: "text",   placeholder: "e.g. OD-998877" },
    { key: "order_amount",        label: "Order amount (₹)",                      type: "number", placeholder: "e.g. 1500" },
    { key: "issue",               label: "Issue",                                 type: "select",
      options: ["Not delivered", "Wrong item", "Refund denied", "Damaged", "Counterfeit", "Subscription cancelled but charged", "Data breach/privacy"] },
    { key: "purchase_date",       label: "Date of purchase",                      type: "date" },
    { key: "refund_requested",    label: "Refund requested?",                     type: "yesno" },
    { key: "amount_disputed",     label: "Amount in dispute (₹)",                 type: "number", placeholder: "e.g. 1500" },
    { key: "seller_type",         label: "Seller Type",                           type: "select",
      options: ["Directly from platform (Amazon Retail, Flipkart itself)", "Third-party seller on platform", "Not sure"] },
    { key: "return_window_still_open", label: "Was return window open when issue was raised?", type: "yesno" },
    { key: "nch_complaint_filed", label: "Was a National Consumer Helpline (NCH) complaint filed?", type: "yesno" },
    { key: "evidence_of_issue",   label: "What evidence is available?",           type: "select",
      options: ["Photos of damaged/wrong item", "Screenshot of order confirmation", "Delivery proof/tracking", "Chat transcript with support"] },
    { key: "seller_name_on_platform", label: "Seller name on platform",           type: "text", placeholder: "e.g. Retailer X" },
  ],
  insurance_rejection: [
    { key: "insurance_type",      label: "Insurance type",                        type: "select",
      options: ["Health", "Motor", "Life", "Home", "Travel"] },
    { key: "insurance_company",   label: "Insurance company",                     type: "text",   placeholder: "e.g. Star Health" },
    { key: "policy_number",       label: "Policy number",                         type: "text",   placeholder: "e.g. STAR-9988" },
    { key: "claim_amount",        label: "Claim amount (₹)",                      type: "number", placeholder: "e.g. 150000" },
    { key: "reason_for_rejection",label: "Primary reason for rejection",          type: "select",
      options: ["Pre-existing disease exclusion", "Non-disclosure of medical history", "Policy lapse / non-payment of premium", "Claim filed beyond time limit", "Non-standard treatment / non-network hospital", "Policy exclusion (adventure sport, war, etc.)", "Misrepresentation in proposal form", "Other"] },
    { key: "date_of_rejection",   label: "Date of rejection",                     type: "date" },
    { key: "date_of_incident",    label: "Date of incident",                      type: "date" },
    { key: "policy_inception_date", label: "Policy start (inception) date",       type: "date" },
    { key: "claim_filing_delay_days", label: "Filing delay (days elapsed)",       type: "number", placeholder: "e.g. 10" },
    { key: "irdai_ombudsman_filed", label: "Was IRDAI Insurance Ombudsman approached?", type: "yesno" },
    { key: "cashless_or_reimbursement", label: "Claim Type",                      type: "select",
      options: ["Cashless claim denied", "Reimbursement claim denied", "Both"] },
    { key: "gro_complaint_filed", label: "Was Grievance Redressal Officer (GRO) approached?", type: "yesno" },
    { key: "policy_term_years",   label: "Policy active term (years)",            type: "number", placeholder: "e.g. 3" },
    { key: "premium_payment_up_to_date", label: "Are premium payments up-to-date?", type: "yesno" },
  ],
  medical_negligence: [
    { key: "hospital_doctor_name",label: "Hospital/Doctor name",                  type: "text",   placeholder: "e.g. Apollo Hospital" },
    { key: "treatment_date",      label: "Date of treatment",                     type: "date" },
    { key: "medical_bills",       label: "Medical bills incurred (₹)",            type: "number", placeholder: "e.g. 350000" },
    { key: "complaint_to_hospital",label: "Complaint submitted to hospital?",      type: "yesno" },
    { key: "state_medical_council_complaint", label: "Complaint sent to State Medical Council?", type: "yesno" },
    { key: "harm_caused",         label: "Harm caused",                           type: "select",
      options: ["Permanent disability", "Temporary disability requiring ongoing treatment", "Death", "Worsened condition", "Unnecessary procedure / wrong limb / wrong organ", "Medication error", "Infection / hospital-acquired illness"] },
    { key: "patient_name",        label: "Patient name",                          type: "text",   placeholder: "e.g. Ramesh Verma" },
    { key: "patient_age",         label: "Patient age",                           type: "number", placeholder: "e.g. 45" },
    { key: "expert_opinion_obtained", label: "Do you have an independent medical expert opinion?", type: "yesno" },
    { key: "procedure_type",      label: "Procedure Type",                        type: "select",
      options: ["Surgery", "Diagnosis (missed/wrong)", "Medication error", "Childbirth/Obstetric", "Emergency care", "Post-operative care", "Anesthesia", "Dental procedure"] },
    { key: "patient_outcome",     label: "Patient Outcome",                       type: "select",
      options: ["Death", "Permanent disability (specify %)", "Temporary disability, now recovered", "Still under treatment", "Worsened chronic condition"] },
    { key: "medical_records_available", label: "Are medical records accessible?",  type: "select",
      options: ["Complete records obtained", "Partial records (hospital blocking access)", "No records obtained yet"] },
    { key: "informed_consent_obtained", label: "Was informed consent form signed?", type: "yesno" },
    { key: "hospital_type",       label: "Hospital Type",                         type: "select",
      options: ["Private hospital", "Government hospital", "Diagnostic lab", "Individual doctor (private clinic)", "Nursing home"] },
  ],
  delayed_possession: [
    { key: "project_name",        label: "Project name",                          type: "text",   placeholder: "e.g. DLF Heights" },
    { key: "builder_name",        label: "Builder name",                          type: "text",   placeholder: "e.g. DLF Ltd" },
    { key: "rera_registration",   label: "RERA registration number",              type: "text",   placeholder: "e.g. RERA-12345" },
    { key: "flat_number",         label: "Flat/unit number",                      type: "text",   placeholder: "e.g. B-402" },
    { key: "total_flat_cost",     label: "Total flat cost (₹)",                   type: "number", placeholder: "e.g. 7500000" },
    { key: "amount_paid",         label: "Amount paid so far (₹)",                type: "number", placeholder: "e.g. 5000000" },
    { key: "promised_possession_date", label: "Promised possession date",         type: "date" },
    { key: "current_status",      label: "Current project status",                type: "select",
      options: ["Under construction", "Abandoned", "Partial handover", "OC received but builder not handing over"] },
    { key: "demand_letters_sent", label: "Demand letters sent to builder?",       type: "yesno" },
    { key: "state_rera",          label: "State RERA authority",                  type: "text",   placeholder: "e.g. Karnataka RERA" },
    { key: "relief_preference",   label: "Relief Preference (RERA Sec 18)",       type: "select",
      options: ["Want possession with interest for delay", "Want full refund with interest", "Not sure, need advice"] },
    { key: "allotment_letter_available", label: "Is allotment letter available?",  type: "yesno" },
    { key: "sale_agreement_available", label: "Is signed Agreement for Sale available?", type: "yesno" },
    { key: "financed_by_bank_loan", label: "Is flat purchase financed by home loan?", type: "yesno" },
    { key: "rera_complaint_already_filed", label: "Is a formal RERA portal complaint already filed?", type: "yesno" },
    { key: "carpet_area_sqft",    label: "Flat carpet area (sqft)",               type: "number", placeholder: "e.g. 1100" },
    { key: "oc_received_by_builder", label: "Has builder received Occupancy Certificate?", type: "yesno" },
    { key: "additional_charges_demanded", label: "Is builder demanding additional non-agreed fees?", type: "yesno" },
  ],
  project_cancellation: [
    { key: "project_name",        label: "Project name",                          type: "text",   placeholder: "e.g. Prestige Lakeview" },
    { key: "builder_name",        label: "Builder",                               type: "text",   placeholder: "e.g. Prestige Group" },
    { key: "booking_amount",      label: "Booking amount paid (₹)",               type: "number", placeholder: "e.g. 500000" },
    { key: "cancellation_date",   label: "Date of cancellation",                  type: "date" },
    { key: "refund_received",     label: "Refund received?",                      type: "yesno" },
    { key: "amount_refunded",     label: "Amount refunded (₹)",                   type: "number", placeholder: "e.g. 200000" },
    { key: "cancellation_reason",  label: "Reason given by builder",               type: "text",   placeholder: "e.g. Clearances rejected" },
    { key: "who_cancelled",       label: "Who cancelled the booking?",            type: "select",
      options: ["Builder/developer cancelled", "I (buyer) cancelled due to builder's default", "Mutual cancellation", "Not clear"] },
    { key: "allotment_letter_available", label: "Is booking allotment letter available?", type: "yesno" },
    { key: "legal_notice_sent_to_builder", label: "Was formal notice sent to builder demanding refund?", type: "yesno" },
    { key: "builder_rera_registered", label: "Is/was the project RERA registered?", type: "yesno" },
    { key: "completion_percentage_at_cancellation", label: "Project status at cancellation", type: "select",
      options: ["0-25%", "26-50%", "51-75%", "75-100%"] },
    { key: "interest_demanded_on_refund", label: "Do you claim interest on refund?", type: "yesno" },
  ],
  structural_defects: [
    { key: "project_name",        label: "Project name",                          type: "text",   placeholder: "e.g. Sobha Royal" },
    { key: "builder_name",        label: "Builder",                               type: "text",   placeholder: "e.g. Sobha Ltd" },
    { key: "possession_date",     label: "Possession date received",              type: "date" },
    { key: "defect_description",  label: "Defect type",                           type: "select",
      options: ["Water seepage / dampness", "Wall / column cracks (structural)", "Roof leakage", "Plumbing defects (pipes, drainage)", "Electrical wiring faults", "Floor/tile de-bonding", "Door/window alignment issues", "Elevator defects"] },
    { key: "defect_noticed_date", label: "Defect noticed date",                   type: "date" },
    { key: "repair_demanded",     label: "Repair demanded?",                      type: "yesno" },
    { key: "builder_responded",   label: "Builder responded?",                      type: "yesno" },
    { key: "possession_date_verified", label: "Is possession date supported by handover letter?", type: "yesno" },
    { key: "five_year_warranty_check", label: "Is defect within 5 years of possession?", type: "yesno" },
    { key: "oc_received",         label: "Did builder obtain OC before handover?", type: "yesno" },
    { key: "independent_expert_assessed", label: "Did independent engineer document the defects?", type: "yesno" },
    { key: "defect_affected_area", label: "Affected structural area details",      type: "text", placeholder: "e.g. Bathroom ceiling, master bedroom wall" },
    { key: "builder_partially_repaired", label: "Did builder attempt a partial/failed repair?", type: "yesno" },
  ],
  amenities_misrepresentation: [
    { key: "project_name",        label: "Project name",                          type: "text",   placeholder: "e.g. Godrej Eternity" },
    { key: "builder_name",        label: "Builder",                               type: "text",   placeholder: "e.g. Godrej Properties" },
    { key: "promised_amenity",    label: "Promised amenity",                      type: "text",   placeholder: "e.g. Clubhouse and pool" },
    { key: "what_not_delivered",  label: "What was not delivered",                type: "text",   placeholder: "e.g. Clubhouse and pool" },
    { key: "promise_documented",  label: "Where was promise documented?",         type: "select",
      options: ["Sale Agreement (brochure attached or listed)", "Advertising brochure", "Builder website screenshots", "Verbal promise (no documentation)", "WhatsApp/email communication from builder"] },
    { key: "rera_registration_number", label: "RERA Registration Number",         type: "text", placeholder: "e.g. PRM/KA/RERA/..." },
    { key: "amenity_type",        label: "Amenity Category",                      type: "select",
      options: ["Sports/Recreation (pool, gym, club)", "Infrastructure (parking, lift, generator)", "Green spaces (park, garden)", "Commercial facility (retail, medical)", "Security features", "Educational facility"] },
    { key: "date_sale_agreement_signed", label: "Date Agreement for Sale was signed", type: "date" },
    { key: "other_buyers_affected", label: "Are other homebuyers in the project affected?", type: "yesno" },
    { key: "delivery_date_for_amenity", label: "Promised delivery date for amenity", type: "text", placeholder: "e.g. Dec 2026" },
  ],
  accident_injury: [
    { key: "accident_date",       label: "Accident date",                         type: "date" },
    { key: "accident_location",   label: "Accident location",                     type: "text",   placeholder: "e.g. Outer Ring Road, Delhi" },
    { key: "your_role",           label: "Your role",                             type: "select",
      options: ["Driver", "Pedestrian", "Passenger", "Bystander"] },
    { key: "vehicle_involved",    label: "Vehicle involved (type + registration)",type: "text",   placeholder: "e.g. Sedan (DL-3C-XX-XXXX)" },
    { key: "fir_filed",           label: "FIR filed?",                            type: "yesno" },
    { key: "fir_number",          label: "FIR number",                            type: "text",   placeholder: "e.g. FIR/123/2025" },
    { key: "police_station",      label: "Police station",                        type: "text",   placeholder: "e.g. Saket Police Station" },
    { key: "injuries_sustained",  label: "Injuries sustained",                    type: "select",
      options: ["Minor injuries (no hospitalization)", "Fracture / dislocation", "Permanent partial disability", "Permanent total disability", "Head/brain injury", "Spinal cord injury", "Burns (specify %)"] },
    { key: "hospital_treatment",  label: "Hospital treatment taken?",             type: "yesno" },
    { key: "hospital_name",       label: "Hospital name",                         type: "text",   placeholder: "e.g. Max Hospital" },
    { key: "medical_expenses",    label: "Medical expenses incurred (₹)",          type: "number", placeholder: "e.g. 85000" },
    { key: "income_lost",         label: "Monthly income BEFORE accident (₹)",    type: "number", placeholder: "e.g. 45000" },
    { key: "claimant_age",        label: "Age of claimant",                       type: "number", placeholder: "e.g. 30" },
    { key: "employment_type",     label: "Employment Type",                       type: "select",
      options: ["Salaried (permanent/regular)", "Self-employed / business", "Daily wages / casual labour", "Student", "Homemaker", "Unemployed / retired"] },
    { key: "disability_percentage", label: "Doctor-assessed Disability (%)",     type: "number", placeholder: "e.g. 40" },
    { key: "offending_vehicle_registration", label: "Offending vehicle registration number", type: "text", placeholder: "e.g. MH-02-AB-1234" },
    { key: "offending_vehicle_insurer", label: "Offending vehicle insurer",       type: "text", placeholder: "e.g. ICICI Lombard" },
    { key: "six_month_limitation_check", label: "Is filing within 6 months of accident?", type: "yesno" },
    { key: "detailed_accident_report_received", label: "Was Detailed Accident Report (DAR) filed by police?", type: "yesno" },
    { key: "own_insurance_claim_filed", label: "Own vehicle insurance claim filed?", type: "yesno" },
    { key: "interim_compensation_needed", label: "Is interim (immediate) compensation requested?", type: "yesno" },
  ],
  accident_death: [
    { key: "accident_date",       label: "Accident date",                         type: "date" },
    { key: "deceased_name",       label: "Deceased name",                         type: "text",   placeholder: "e.g. Ramesh Verma" },
    { key: "relationship_to_claimant", label: "Relationship to claimant",         type: "text",   placeholder: "e.g. Spouse / Dependent child" },
    { key: "fir_number",          label: "FIR number",                            type: "text",   placeholder: "e.g. FIR/456/2025" },
    { key: "dependents",          label: "Are there dependents?",                  type: "yesno" },
    { key: "dependents_count",    label: "Number of dependants",                  type: "number", placeholder: "e.g. 3" },
    { key: "deceased_income",     label: "Deceased's monthly income (₹) — salary slips/ITR needed", type: "number", placeholder: "e.g. 60000" },
    { key: "offending_vehicle_insurer", label: "Offending vehicle insurer",       type: "text", placeholder: "e.g. National Insurance" },
    { key: "date_of_death",       label: "Date of death",                         type: "date" },
    { key: "deceased_age",        label: "Age of deceased",                       type: "number", placeholder: "e.g. 42" },
    { key: "deceased_employment_type", label: "Deceased's Employment Type",       type: "select",
      options: ["Salaried (permanent)", "Self-employed / business", "Daily wages", "Homemaker (notional income)", "Student", "Retired"] },
    { key: "deceased_marital_status", label: "Deceased's Marital Status",         type: "select",
      options: ["Married", "Unmarried/Bachelor", "Widowed/Divorced"] },
    { key: "post_mortem_done",    label: "Was post-mortem conducted?",            type: "yesno" },
    { key: "legal_heir_certificate_obtained", label: "Is Legal Heir Certificate obtained?", type: "yesno" },
    { key: "offending_vehicle_registration", label: "Offending vehicle registration number", type: "text", placeholder: "e.g. DL-1C-A-1111" },
    { key: "surviving_spouse_income", label: "Surviving spouse monthly income (₹)", type: "number", placeholder: "e.g. 20000" },
    { key: "vehicle_type_deceased_was_on", label: "Deceased was traveling via",   type: "select",
      options: ["Pedestrian (not on any vehicle)", "Two-wheeler (rider)", "Two-wheeler (pillion)", "Car (driver)", "Car (passenger)", "Auto/taxi (passenger)", "Commercial vehicle (driver/helper)"] },
  ],
  mv_insurance_rejection: [
    { key: "insurance_company",   label: "Insurance company",                     type: "text",   placeholder: "e.g. ICICI Lombard" },
    { key: "policy_number",       label: "Policy number",                         type: "text",   placeholder: "e.g. M-998877" },
    { key: "claim_type",          label: "Claim type",                            type: "select",
      options: ["Own damage", "Third party", "Comprehensive", "Personal accident cover", "Theft claim"] },
    { key: "vehicle_registration",label: "Vehicle registration",                  type: "text",   placeholder: "e.g. KA-03-XX-YYYY" },
    { key: "reason_for_rejection",label: "Reason for rejection",                  type: "text",   placeholder: "e.g. Unauthorized driver license" },
    { key: "claim_amount",        label: "Claim amount (₹)",                      type: "number", placeholder: "e.g. 95000" },
    { key: "date_of_rejection",   label: "Date of rejection",                     type: "date" },
    { key: "vehicle_type",        label: "Vehicle type",                          type: "select",
      options: ["Two-wheeler", "Car/SUV", "Commercial vehicle (truck/bus)", "Auto-rickshaw"] },
    { key: "fir_filed",           label: "Was FIR filed for accident/theft?",     type: "yesno" },
    { key: "survey_report_obtained", label: "Was surveyor report copy obtained?", type: "yesno" },
    { key: "irdai_ombudsman_filed", label: "Was IRDAI Insurance Ombudsman approached?", type: "yesno" },
    { key: "accident_or_theft",   label: "Dispute incident trigger",              type: "select",
      options: ["Road accident claim", "Own damage (parked vehicle)", "Theft of vehicle", "Fire damage", "Natural disaster damage"] },
    { key: "was_vehicle_insured_at_time", label: "Was policy active at time of incident?", type: "yesno" },
    { key: "driver_was_licensed", label: "Did driver have a valid driving licence?", type: "yesno" },
  ],
  hit_and_run: [
    { key: "accident_date",       label: "Date of accident",                      type: "date" },
    { key: "accident_location",   label: "Location",                              type: "text",   placeholder: "e.g. Hosur Road, Bangalore" },
    { key: "vehicle_description", label: "Vehicle description (if known)",        type: "text",   placeholder: "e.g. Black SUV" },
    { key: "fir_filed",           label: "FIR filed?",                            type: "yesno" },
    { key: "police_station",      label: "Police station",                        type: "text",   placeholder: "e.g. Electronic City PS" },
    { key: "mact_compensation_applied", label: "Applied for compensation from Motor Vehicle Accident Fund?", type: "yesno" },
    { key: "injuries_fatality",   label: "Injuries / fatality severity",          type: "select",
      options: ["Grievous hurt requiring hospitalization", "Fatal (death of victim)", "Permanent disability", "Minor injuries (no hospitalization)"] },
    { key: "victim_alive_or_deceased", label: "Victim status",                     type: "select",
      options: ["Alive (victim filing)", "Deceased (family filing)"] },
    { key: "medical_expenses",    label: "Medical expenses incurred (₹)",          type: "number", placeholder: "e.g. 50000" },
    { key: "hospital_treatment",  label: "Was emergency hospital treatment received?", type: "yesno" },
    { key: "vehicle_later_identified", label: "Was offending vehicle identified later?", type: "yesno" },
    { key: "claim_enquiry_officer_approached", label: "Was District Claim Enquiry Officer approached?", type: "yesno" },
  ],
  license_rc_dispute: [
    { key: "dispute_type",        label: "Dispute type",                          type: "select",
      options: ["Licence suspended", "RC cancelled", "Penalty dispute", "Transfer dispute"] },
    { key: "authority_involved",  label: "Authority involved (RTO name)",          type: "text",   placeholder: "e.g. Indiranagar RTO" },
    { key: "notice_received",     label: "Notice received?",                      type: "yesno" },
    { key: "order_date",          label: "Date of order",                         type: "date" },
    { key: "licence_type",        label: "Licence type category",                 type: "select",
      options: ["LMV (car/jeep)", "Two-wheeler only", "HMV (truck/bus)", "Commercial passenger vehicle", "All categories"] },
    { key: "suspension_reason",   label: "Suspension Reason",                     type: "select",
      options: ["Drunk driving / DUI", "Road accident involvement", "Non-payment of fine/penalty", "Falsification of documents", "Failure to appear for renewal", "Court order"] },
    { key: "order_in_writing",    label: "Was official order given in writing?",  type: "yesno" },
    { key: "penalty_amount",      label: "Disputed penalty amount (₹)",           type: "number", placeholder: "e.g. 10000" },
    { key: "driving_livelihood",  label: "Does your livelihood depend on license/RC?", type: "yesno" },
    { key: "prior_violations",    label: "Are there other driving violations on record?", type: "yesno" },
  ],
};
